<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\ClassificationBundle\Entity\Classification;

use Sonata\ClassificationBundle\Entity\BaseContext as BaseContext;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( https://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Context extends BaseContext {

    /**
     * @var string $id
     */
    protected $id;

    /**
     * @var \Application\Sonata\UserBundle\Entity\User\User
     */
    private $owner;

    /**
     * Get id
     *
     * @return string $id
     */
    public function getId() {
        return $this->id;
    }

    public function __toString() {
        return $this->getName() ? $this->getName() : 'n/a';
    }

    /**
     * Set owner
     *
     * @param \Application\Sonata\UserBundle\Entity\User\User $owner
     *
     * @return Context
     */
    public function setOwner(\Application\Sonata\UserBundle\Entity\User\User $owner = null) {
        $this->owner = $owner;

        return $this;
    }

    /**
     * Get owner
     *
     * @return \Application\Sonata\UserBundle\Entity\User\User
     */
    public function getOwner() {
        return $this->owner;
    }

}
